### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by hegaojian** [OBKoro1/autoCommit#10]
如果不手动指定日期范围（手动太累，而且总有种习惯规律）的话，绿墙全部都占满咯，看着有点太假的感觉，自己看着都不好意思:relaxed:，希望能添加随机日期提交，比如说指定一个时间范围，2020-1-1 - 2020-8-20，能随机部分天数不提交，看着无规律

**Comment by OBKoro1** [comment]
好的 我过几天 加一下这个功能哈

**Comment by OBKoro1** [comment]
@hegaojian 更新插件，这个功能加好了。

**Comment by hegaojian** [comment]
大佬给力！ 666

**Comment by hegaojian** [comment]
这个超出时间范围是如何定义的呢，不是很理解

**Comment by OBKoro1** [comment]
文档: [间隔提交](https://github.com/OBKoro1/autoCommit/wiki/%E9%85%8D%E7%BD%AE%E5%8F%8A%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E9%97%B4%E9%9A%94%E6%8F%90%E4%BA%A4)
