### ISSUE TITLE
插件好像不能用了？

### ISSUE THREAD

**Issue by zephyr-fun** [OBKoro1/autoCommit#14]
昨天写了东西，结果忘了提交，今天想用auto commit弥补一下，结果发现失败了，心态炸裂。想辛苦问下作者，github是把这个封禁了嘛，或者说您有没有更新的计划？

**Comment by OBKoro1** [comment]
你好，请按照issue规范 再提交一下，没有信息无法判断。

**Comment by OBKoro1** [comment]
@zephyr-fun 更新插件 现已修复该问题，记得帮忙点个Star~
