### ISSUE TITLE
push不了

### ISSUE THREAD

**Issue by nateshao** [OBKoro1/autoCommit#15]
win提交的记录，手动可以修改，

提交中...
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-29T04:43:00+08:00' GIT_AUTHOR_DATE='2020-06-29T04:43:00+08:00' git commit --amend --no-edit --date '2020-06-29T04:43:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-29T04:43:00+08:00' GIT_AUTHOR_DATE='2020-06-29T04:43:00+08:00' git commit --amend --no-edit --date '2020-06-29T04:43:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

执行命令出错:git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-29T04:43:00+08:00' GIT_AUTHOR_DATE='2020-06-29T04:43:00+08:00' git commit --amend --no-edit --date '2020-06-29T04:43:00+08:00'
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-28T15:58:00+08:00' GIT_AUTHOR_DATE='2020-06-28T15:58:00+08:00' git commit --amend --no-edit --date '2020-06-28T15:58:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-28T15:58:00+08:00' GIT_AUTHOR_DATE='2020-06-28T15:58:00+08:00' git commit --amend --no-edit --date '2020-06-28T15:58:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

执行命令出错:git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-28T15:58:00+08:00' GIT_AUTHOR_DATE='2020-06-28T15:58:00+08:00' git commit --amend --no-edit --date '2020-06-28T15:58:00+08:00'
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-27T12:53:00+08:00' GIT_AUTHOR_DATE='2020-06-27T12:53:00+08:00' git commit --amend --no-edit --date '2020-06-27T12:53:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-27T12:53:00+08:00' GIT_AUTHOR_DATE='2020-06-27T12:53:00+08:00' git commit --amend --no-edit --date '2020-06-27T12:53:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

执行命令出错:git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-27T12:53:00+08:00' GIT_AUTHOR_DATE='2020-06-27T12:53:00+08:00' git commit --amend --no-edit --date '2020-06-27T12:53:00+08:00'
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-26T01:26:00+08:00' GIT_AUTHOR_DATE='2020-06-26T01:26:00+08:00' git commit --amend --no-edit --date '2020-06-26T01:26:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-26T01:26:00+08:00' GIT_AUTHOR_DATE='2020-06-26T01:26:00+08:00' git commit --amend --no-edit --date '2020-06-26T01:26:00+08:00'
warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 warning: LF will be replaced by CRLF in commit.md.
The file will have its original line endings in your working directory
'GIT_COMMITTER_DATE' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

执行命令出错:git add . && git commit -m 'autoCommit' && GIT_COMMITTER_DATE='2020-06-26T01:26:00+08:00' GIT_AUTHOR_DATE='2020-06-26T01:26:00+08:00' git commit --amend --no-edit --date '2020-06-26T01:26:00+08:00'
总commit次数: 4
总commit天数: 4
将要commit的日期: [{"value":"2020-06-26","commitNumber":1},{"value":"2020-06-27","commitNumber":1},{"value":"2020-06-28","commitNumber":1},{"value":"2020-06-29","commitNumber":1}]

**Comment by OBKoro1** [comment]
@nateshao 更新插件 现已修复该问题，记得帮我点个Star呀~
