### ISSUE TITLE
谷歌浏览器打开好像没什么问题，但是换了个火狐浏览器去没效果哦，别人看到我的GitHub也是没效果

### ISSUE THREAD

**Issue by nateshao** [OBKoro1/autoCommit#16]
## 第一
- GitHub提交成功，谷歌可以看到，但是火狐浏览器没效果，别人打开，也看不到我的绿点
## 第二
- gitee是没问题的
## 第三
- gitlab没效果

**Comment by nateshao** [comment]
[![sBMe1K.png](https://s3.ax1x.com/2021/01/15/sBMe1K.png)](https://imgchr.com/i/sBMe1K)
[![sBMm6O.png](https://s3.ax1x.com/2021/01/15/sBMm6O.png)](https://imgchr.com/i/sBMm6O)

**Comment by OBKoro1** [comment]
**由于没有打开github的私有仓库贡献可见，所以只能自己看到**

![871611034112_ pic_hd](https://user-images.githubusercontent.com/24698201/104992519-2b026380-5a5c-11eb-82a0-f3e323e2bd8f.jpg)
