### ISSUE TITLE
安装后找不到插件

### ISSUE THREAD

**Issue by Alessandro-Pang** [OBKoro1/autoCommit#2]
如题，安装该插件后找不到；
![小Q截图-20200114084237](https://user-images.githubusercontent.com/42641570/72304108-83b15a80-36aa-11ea-9090-bac2920adbff.png)
![小Q截图-20200114084252](https://user-images.githubusercontent.com/42641570/72304109-8449f100-36aa-11ea-8bdc-eabd2e99f102.png)
![小Q截图-20200114084218](https://user-images.githubusercontent.com/42641570/72304110-84e28780-36aa-11ea-979f-289f00879225.png)

**Comment by WangShayne** [comment]
ctrl + shift + p

**Comment by OBKoro1** [comment]
输入`> auto commit`，少了一个`>`
