### ISSUE TITLE
win10，还是跟之前一样报错

### ISSUE THREAD

**Issue by SuT2i** [OBKoro1/autoCommit#25]
#### 描述bug(必填)
vsc上手动可以提交推送
#### 插件运行日志(必填):
数据: git push失败很可能是你的网络有问题，请换到一个网络状况比较良好的地方，然后再项目下执行 git push操作。
command: console-log
git push失败很可能是你的网络有问题，请换到一个网络状况比较良好的地方，然后再项目下执行 git push操作。
数据: 错误信息:Error: Command failed: git pull --rebase  && git push
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
,'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
错误信息:Error: Command failed: git pull --rebase  && git push
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 执行命令出错:git pull --rebase  && git push
command: console-log
执行命令出错:git pull --rebase  && git push
数据: 提交中
command: 提交中...
数据: 提交中...
command: console-log
提交中...
数据: commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
,'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
command: console-log
执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T15:09:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T15:09:00+08:00' && git commit --amend --no-edit --date '2021-05-02T15:09:00+08:00'
数据: commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
,'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
command: console-log
执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-02T23:37:00+08:00' && set GIT_AUTHOR_DATE='2021-05-02T23:37:00+08:00' && git commit --amend --no-edit --date '2021-05-02T23:37:00+08:00'
数据: commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
,'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
command: console-log
执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T14:38:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T14:38:00+08:00' && git commit --amend --no-edit --date '2021-05-01T14:38:00+08:00'
数据: commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
commit出错:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
,'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

command: console-log
错误信息:Error: Command failed: git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

数据: 执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
command: console-log
执行命令出错:git add . && git commit -m 'autoCommit' && set GIT_COMMITTER_DATE='2021-05-01T07:11:00+08:00' && set GIT_AUTHOR_DATE='2021-05-01T07:11:00+08:00' && git commit --amend --no-edit --date '2021-05-01T07:11:00+08:00'
数据: 总commit次数:,4
command: console-log
总commit次数: 4
数据: 总commit天数:,2
command: console-log
总commit天数: 2
数据: 将要commit的日期:,[{"value":"2021-05-01","commitNumber":2},{"value":"2021-05-02","commitNumber":2}]
command: console-log
将要commit的日期: [{"value":"2021-05-01","commitNumber":2},{"value":"2021-05-02","commitNumber":2}]
```

#### 程序运行参数(必填):
{"randomCommit":true,"itemSrc":"c:\\Users\\Xinteng\\Desktop\\dev airdrop\\dev-","fileName":"commit.md","commitMsg":"autoCommit","timeArr":[{"value":["2021-05-01","2021-05-02"],"commitNumber":2}],"commitNumber":2}

```js
// 参数
```

### 分支名

master

**Comment by OBKoro1** [comment]
我刚才试了一下 是可以的，你先看看自己用命令行操作是否正常，不行的话，建议仓库删了，再clone一遍，重新操作。

**Comment by seven-lyw** [comment]
还是报错，确实插件下载下来确实有这个问题！

**Comment by OBKoro1** [comment]
> 还是报错，确实插件下载下来确实有这个问题！

我是说 你先看要提交的那个仓库 能不能正常提交，我今天试了两次都是可以的🤣

**Comment by arcsin3x** [comment]
> 
> 
> > 还是报错，确实插件下载下来确实有这个问题！
> 
> 我是说 你先看要提交的那个仓库 能不能正常提交，我今天试了两次都是可以的rofl

你好，我想问下怎么随机日期，就是在一段时间内随机某一天进行commit

**Comment by OBKoro1** [comment]
@arcsin3x 
![image](https://user-images.githubusercontent.com/24698201/120258595-ecf83480-c2c4-11eb-9381-de27ea62044e.png)

**Comment by tuzinapc** [comment]
我也是这样 lz解决了么？

**Comment by OBKoro1** [comment]
@SuT2i  @lywlefan  @arcsin3x  @tuzinapc  更新一下最新版本，这个问题已经被修复，现在可以正常在首页显示绿点了。我将关闭这个issue,有问题的话，可以再开个issue 沟通。

开源不易，如果觉得插件做的还不错的话，请给我点个star吧~
