### ISSUE TITLE
win10 请选择要commit的项目文件夹

### ISSUE THREAD

**Issue by miaobei5555** [OBKoro1/autoCommit#27]
win10 一直提示这个 根本 用不了啊

**Comment by OBKoro1** [comment]
建议先看下[文档](https://github.com/OBKoro1/autoCommit/wiki/%E9%85%8D%E7%BD%AE%E5%8F%8A%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
如果还是不行的话，请按照issue规范提issue。
