### ISSUE TITLE
Win10 提交出错

### ISSUE THREAD

**Issue by hardlyh** [OBKoro1/autoCommit#3]
报错信息:
保存参数信息
自动commit完成 总commit次数0
提交信息: Already up to date.

提交中...
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 03:23'
error: pathspec '03:23'' did not match any file(s) known to git
 error: pathspec '03:23'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 03:23'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 06:08'
error: pathspec '06:08'' did not match any file(s) known to git
 error: pathspec '06:08'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 06:08'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 07:53'
error: pathspec '07:53'' did not match any file(s) known to git
 error: pathspec '07:53'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 07:53'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 02:27'
error: pathspec '02:27'' did not match any file(s) known to git
 error: pathspec '02:27'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 02:27'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 07:02'
error: pathspec '07:02'' did not match any file(s) known to git
 error: pathspec '07:02'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 07:02'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 08:36'
error: pathspec '08:36'' did not match any file(s) known to git
 error: pathspec '08:36'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 08:36'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 23:34'
error: pathspec '23:34'' did not match any file(s) known to git
 error: pathspec '23:34'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 23:34'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 16:15'
error: pathspec '16:15'' did not match any file(s) known to git
 error: pathspec '16:15'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 16:15'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 15:18'
error: pathspec '15:18'' did not match any file(s) known to git
 error: pathspec '15:18'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-14 15:18'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 15:21'
error: pathspec '15:21'' did not match any file(s) known to git
 error: pathspec '15:21'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 15:21'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 20:17'
error: pathspec '20:17'' did not match any file(s) known to git
 error: pathspec '20:17'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 20:17'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 22:36'
error: pathspec '22:36'' did not match any file(s) known to git
 error: pathspec '22:36'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 22:36'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 17:47'
error: pathspec '17:47'' did not match any file(s) known to git
 error: pathspec '17:47'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 17:47'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 08:07'
error: pathspec '08:07'' did not match any file(s) known to git
 error: pathspec '08:07'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 08:07'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 19:45'
error: pathspec '19:45'' did not match any file(s) known to git
 error: pathspec '19:45'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 19:45'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 20:44'
error: pathspec '20:44'' did not match any file(s) known to git
 error: pathspec '20:44'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 20:44'
错误信息:Error: Command failed: cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 19:08'
error: pathspec '19:08'' did not match any file(s) known to git
 error: pathspec '19:08'' did not match any file(s) known to git

执行命令出错:cd e:\work\gongsi_worl_git\autoCommit && git add . && git commit -m 'autoCommit' --date='2020-01-13 19:08'
将要commit的日期: [{"value":"2020-01-13","commitNumber":0},{"value":"2020-01-14","commitNumber":0}]

插件参数:
{
    "randomCommit": true,
    "itemSrc": "e:\\work\\gongsi_worl_git\\autoCommit",
    "fileName": "commit.md",
    "commitMsg": "autoCommit",
    "timeArr": [
    {
        "value": ["2020-01-13", "2020-01-14"],
        "commitNumber": 0
    }],
    "commitNumber": 10
}

文件Push情况:
使用命令行是确保可以push成功的,如下图.

![image](https://user-images.githubusercontent.com/22518278/72415398-5b5f5400-37af-11ea-9cd7-718fb1f371d1.png)

**Comment by OBKoro1** [comment]
最新版本已修复该问题，如果觉得本插件还不错的话给个Star吧~
