### ISSUE TITLE
当 update 时，自动或定时 commit/push

### ISSUE THREAD

**Issue by siu91** [OBKoro1/autoCommit#32]
我的需求是这样的，用 VS Code 作为 markdown 编辑器，当作云笔记使用；VS Code + Github，已经满足基础的需求，还差 auto commit 这样的插件，帮我把更新提交，比如定时下班时间；望采纳。

**Comment by cheakin** [comment]
提交出错了，请问是什么原因？
```
执行命令出错:git commit --date='2022-01-29T11:21:00+08:00' -am 'update my note'
commit出错:Error: Command failed: git commit --date='2022-01-28T21:56:00+08:00' -am 'update my note'
fatal: paths 'my ...' with -a does not make sense

错误信息:Error: Command failed: git commit --date='2022-01-28T21:56:00+08:00' -am 'update my note'
fatal: paths 'my ...' with -a does not make sense
 fatal: paths 'my ...' with -a does not make sense
```

**Comment by OBKoro1** [comment]
@siu91  hi 你好 抱歉 这个功能太定制化了 无法提供

**Comment by OBKoro1** [comment]
> 提交出错了，请问是什么原因？
> 
> ```
> 执行命令出错:git commit --date='2022-01-29T11:21:00+08:00' -am 'update my note'
> commit出错:Error: Command failed: git commit --date='2022-01-28T21:56:00+08:00' -am 'update my note'
> fatal: paths 'my ...' with -a does not make sense
> 
> 错误信息:Error: Command failed: git commit --date='2022-01-28T21:56:00+08:00' -am 'update my note'
> fatal: paths 'my ...' with -a does not make sense
>  fatal: paths 'my ...' with -a does not make sense
> ```

@ckisaboy  hi  你好 请按照规范重新提一个issue
