### ISSUE TITLE
提交当前日期可以自动提交成功，提交历史日期报错

### ISSUE THREAD

**Issue by Chen120322** [OBKoro1/autoCommit#33]
### 注意： 

1. 请先阅读文档: [使用须知](https://github.com/OBKoro1/autoCommit/wiki/%E4%BD%BF%E7%94%A8%E9%A1%BB%E7%9F%A5)(可能该问题已在文档中有过说明)
2. 搜一搜以前关闭的issue看有没有相似的问题可以帮助解决问题。
3. issue提的越清晰，越容易定位问题/找到bug，越快速的解决问题。

#### 描述bug(必填)
提交当前日期可以自动提交成功，提交历史日期报错
#### 插件运行日志(必填):
错误信息:Error: Command failed: git pull --rebase  && git push
fatal: unable to access 'https://github.com/rabbitcccc/test1.git/': Failed to connect to github.com port 443 after 21070 ms: Timed out
 fatal: unable to access 
```js
// 日志内容
```

#### 程序运行参数(必填):

```js
// 参数
```
### Git仓库提交截图

提交成功给个截图
首页的截图

### 分支名

master
#### 屏幕截图(选填)

如果方便的话，添加截图来帮助解释你的问题：

#### 问题相关(选填)

比如`git`的状态: 分支、merge等

**Comment by OBKoro1** [comment]
信息太少无法定位问题，请按照规范重新提一个issue
