### ISSUE TITLE
在windows下有点小bug

### ISSUE THREAD

**Issue by misitebao** [OBKoro1/autoCommit#5]
**您的特性请求是否与问题相关?请描述**

插件里面是直接cd 到指定文件夹，但是windows系统里面假如vscode安装目录和项目所在目录 不在同一个文件夹，这个命令就会报错，提示没有这个目录。

**描述一下你想要的解决方案.**

希望能对这个cd命令做一下win的兼容

**描述你考虑过的备选方案**
对您考虑过的任何替代解决方案或特性的清晰而简明的描述。

**其他相关**
在这里添加关于特性请求的任何其他上下文或屏幕截图。

**Comment by zhangyu9609** [comment]
我就是window下用 一直报错

**Comment by OBKoro1** [comment]
@misitebao @zhangyu9609  无法进入其他磁盘的问题已修复。
