### ISSUE TITLE
虽然设置了勾选了随机，但提交的小绿点都是一个颜色

### ISSUE THREAD

**Issue by ghost** [OBKoro1/autoCommit#6]
#### 描述bug(必填)
如题
#### 插件运行日志(必填):

保存参数信息
自动commit完成 总commit次数7
提交信息: Already up to date.

提交中...
7commit信息 [master c2918cb] 'autoCommit'
 Date: Sat Apr 18 21:51:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

7commit内容 2020-04-18T21:51:00+08:00
随机数:54506
提交次数:7
6commit信息 [master 15a7f8d] 'autoCommit'
 Date: Fri Apr 17 13:15:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

6commit内容 2020-04-17T13:15:00+08:00
随机数:42767
提交次数:6
5commit信息 [master 7dd9540] 'autoCommit'
 Date: Thu Apr 16 15:37:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

5commit内容 2020-04-16T15:37:00+08:00
随机数:28755
提交次数:5
4commit信息 [master 469d10b] 'autoCommit'
 Date: Wed Apr 15 10:02:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

4commit内容 2020-04-15T10:02:00+08:00
随机数:82846
提交次数:4
3commit信息 [master cb4eb60] 'autoCommit'
 Date: Tue Apr 14 20:37:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

3commit内容 2020-04-14T20:37:00+08:00
随机数:23692
提交次数:3
2commit信息 [master 445a31f] 'autoCommit'
 Date: Mon Apr 13 08:14:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

2commit内容 2020-04-13T08:14:00+08:00
随机数:88773
提交次数:2
1commit信息 [master 4c4fcd9] 'autoCommit'
 Date: Sun Apr 12 12:30:00 2020 +0800
 1 file changed, 3 insertions(+), 3 deletions(-)

1commit内容 2020-04-12T12:30:00+08:00
随机数:92126
提交次数:1
将要commit的日期: [{"value":"2020-04-12","commitNumber":1},{"value":"2020-04-13","commitNumber":1},{"value":"2020-04-14","commitNumber":1},{"value":"2020-04-15","commitNumber":1},{"value":"2020-04-16","commitNumber":1},{"value":"2020-04-17","commitNumber":1},{"value":"2020-04-18","commitNumber":1}]
#### 程序运行参数(必填):

{"commitMsg":"autoCommit","commitNumber":14,"fileName":"commit.md","itemSrc":"d:/workspace/fake-commit","randomCommit":true,"timeArr":[{"commitNumber":1,"value":["2020-04-12","2020-04-18"]}]}
#### 怀疑可能是哪里出现问题
可能是随机commit次数没有生效？？？
#### 屏幕截图(选填)

![image](https://user-images.githubusercontent.com/20971456/80558090-a4a87c00-8a0b-11ea-9a38-bb487abaf297.png)
![image](https://user-images.githubusercontent.com/20971456/80558105-b38f2e80-8a0b-11ea-972c-5102c19146f5.png)

#### 问题相关(选填)

无

**Comment by OBKoro1** [comment]
![image](https://user-images.githubusercontent.com/24698201/82414724-15dacc80-9aaa-11ea-8a4a-ff61b54a2bbc.png)
这个值需要为0，否则它会使用这个值。
如果觉得插件还不错的话，可以点个Star呀~
