### ISSUE TITLE
问下那个自动提交工具窗口是怎么打开的 

### ISSUE THREAD

**Issue by hegaojian** [OBKoro1/autoCommit#9]
我是VsCode小白，我按照作者你文档 使用ctrl+p 弹窗，输入auto commit 搜索不到这个插件，但是我在拓展商店里面是已经安装了autoCommit插件了的
![QQ截图20200817104757](https://user-images.githubusercontent.com/18655288/90352860-2b469f00-e077-11ea-92f3-58dc510661d3.png)

**Comment by OBKoro1** [comment]
@hegaojian  `ctrl+p`, 再输入`> auto commit`即可。 `>`符号 需要输入
PS: 喜欢的话 帮忙点个Star吧！

**Comment by hegaojian** [comment]
可以了，非常感谢！！
